/*
                                      * Workflow Executions API
                                      *
                                      * Execute workflows created with Workflows API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::workflowexecutions_v1::models;
use serde::{Deserialize, Serialize};

/// Exception : Exception describes why the step entry failed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Exception {
    /// Error message represented as a JSON string.
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
}

impl Exception {
    /// Exception describes why the step entry failed.
    pub fn new() -> Exception {
        Exception { payload: None }
    }
}
