/*
                                      * Workflow Executions API
                                      *
                                      * Execute workflows created with Workflows API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::workflowexecutions_v1::models;
use serde::{Deserialize, Serialize};

/// ExportDataResponse : Response for the ExportData method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportDataResponse {
    /// The JSON string with customer data and metadata for an execution with the given name
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
}

impl ExportDataResponse {
    /// Response for the ExportData method.
    pub fn new() -> ExportDataResponse {
        ExportDataResponse { data: None }
    }
}
