/*
                                      * Workflow Executions API
                                      *
                                      * Execute workflows created with Workflows API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::workflowexecutions_v1::models;
use serde::{Deserialize, Serialize};

/// ListStepEntriesResponse : Response message for ExecutionHistory.ListStepEntries.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListStepEntriesResponse {
    /// A token to retrieve next page of results. Pass this value in the ListStepEntriesRequest.page_token field in the subsequent call to `ListStepEntries` method to retrieve the next page of results.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// The list of entries.
    #[serde(rename = "stepEntries", skip_serializing_if = "Option::is_none")]
    pub step_entries: Option<Vec<models::StepEntry>>,
    /// Indicates the total number of StepEntries that matched the request filter. For running executions, this number shows the number of StepEntries that are executed thus far.
    #[serde(rename = "totalSize", skip_serializing_if = "Option::is_none")]
    pub total_size: Option<i32>,
}

impl ListStepEntriesResponse {
    /// Response message for ExecutionHistory.ListStepEntries.
    pub fn new() -> ListStepEntriesResponse {
        ListStepEntriesResponse {
            next_page_token: None,
            step_entries: None,
            total_size: None,
        }
    }
}
