/*
                                      * Workflow Executions API
                                      *
                                      * Execute workflows created with Workflows API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::workflowexecutions_v1::models;
use serde::{Deserialize, Serialize};

/// ListCallbacksResponse : RPC response object for the ListCallbacks method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCallbacksResponse {
    /// The callbacks which match the request.
    #[serde(rename = "callbacks", skip_serializing_if = "Option::is_none")]
    pub callbacks: Option<Vec<models::Callback>>,
    /// A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListCallbacksResponse {
    /// RPC response object for the ListCallbacks method.
    pub fn new() -> ListCallbacksResponse {
        ListCallbacksResponse {
            callbacks: None,
            next_page_token: None,
        }
    }
}
