/*
                                      * Workflow Executions API
                                      *
                                      * Execute workflows created with Workflows API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::workflowexecutions_v1::models;
use serde::{Deserialize, Serialize};

/// StackTrace : A collection of stack elements (frames) where an error occurred.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StackTrace {
    /// An array of stack elements.
    #[serde(rename = "elements", skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<models::StackTraceElement>>,
}

impl StackTrace {
    /// A collection of stack elements (frames) where an error occurred.
    pub fn new() -> StackTrace {
        StackTrace { elements: None }
    }
}
