use serde::{Deserialize, Serialize}; /*
                                      * Workflow Executions API
                                      *
                                      * Execute workflows created with Workflows API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// Status : Represents the current status of this execution.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Status {
    /// A list of currently executing or last executed step names for the workflow execution currently running. If the workflow has succeeded or failed, this is the last attempted or executed step. Presently, if the current step is inside a subworkflow, the list only includes that step. In the future, the list will contain items for each step in the call stack, starting with the outermost step in the `main` subworkflow, and ending with the most deeply nested step.
    #[serde(rename = "currentSteps", skip_serializing_if = "Option::is_none")]
    pub current_steps: Option<Vec<crate::google_rest_apis::workflowexecutions_v1::models::Step>>,
}

impl Status {
    /// Represents the current status of this execution.
    pub fn new() -> Status {
        Status {
            current_steps: None,
        }
    }
}
