/*
                                      * Workflow Executions API
                                      *
                                      * Execute workflows created with Workflows API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::workflowexecutions_v1::models;
use serde::{Deserialize, Serialize};

/// Step : Represents a step of the workflow this execution is running.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Step {
    /// Name of a routine within the workflow.
    #[serde(rename = "routine", skip_serializing_if = "Option::is_none")]
    pub routine: Option<String>,
    /// Name of a step within the routine.
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<String>,
}

impl Step {
    /// Represents a step of the workflow this execution is running.
    pub fn new() -> Step {
        Step {
            routine: None,
            step: None,
        }
    }
}
