use serde::{Deserialize, Serialize}; /*
                                      * Workflows API
                                      *
                                      * Manage workflow definitions. To execute workflows and manage executions, see the Workflows Executions API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// ListLocationsResponse : The response message for Locations.ListLocations.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListLocationsResponse {
    /// A list of locations that matches the specified filter in the request.
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<crate::google_rest_apis::workflows_v1::models::Location>>,
    /// The standard List next-page token.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListLocationsResponse {
    /// The response message for Locations.ListLocations.
    pub fn new() -> ListLocationsResponse {
        ListLocationsResponse {
            locations: None,
            next_page_token: None,
        }
    }
}
