use serde::{Deserialize, Serialize}; /*
                                      * Workflows API
                                      *
                                      * Manage workflow definitions. To execute workflows and manage executions, see the Workflows Executions API.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// ListOperationsResponse : The response message for Operations.ListOperations.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListOperationsResponse {
    /// The standard List next-page token.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// A list of operations that matches the specified filter in the request.
    #[serde(rename = "operations", skip_serializing_if = "Option::is_none")]
    pub operations: Option<Vec<crate::google_rest_apis::workflows_v1::models::Operation>>,
}

impl ListOperationsResponse {
    /// The response message for Operations.ListOperations.
    pub fn new() -> ListOperationsResponse {
        ListOperationsResponse {
            next_page_token: None,
            operations: None,
        }
    }
}
